# Generated by Django 2.1.4 on 2019-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
