# Generated by Django 2.1.4 on 2019-01-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dishes_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='quantity',
        ),
    ]
