# Generated by Django 2.1.4 on 2019-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_dishes_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
